### ISSUE TITLE
Imports summaries

### ISSUE THREAD

**Issue by EstrellaFG** [scipion-em/scipion-em-tomo#10]
I have detected that the summaries of the protocols **import tomograms** and **import subtomograms** are not working properly. In both cases I did **not** fill the acquisition info.
In the case of **subtomograms** I got in the summary: `%d format: a number is required, not NoneType`
In the case of **tomograms** I got in the summary: `a float is required`

**Comment by adrianq** [comment]
Fixed with https://github.com/scipion-em/scipion-em-tomo/pull/6/commits/6cf0d1076257276511153c3b3b1b6a293e2e1f1b @EstrellaFG give it a try and reopen this issue the error is still there!
