### ISSUE TITLE
import tomogram viewer

### ISSUE THREAD

**Issue by EstrellaFG** [scipion-em/scipion-em-tomo#11]
Viewer *slices* in import tomograms is not working. I got this:
![Screenshot from 2019-07-11 09-49-29](https://user-images.githubusercontent.com/30145413/61032266-64670700-a3c1-11e9-80cf-6537a2ab598a.png)
But the tomogram is well imported.

**Comment by adrianq** [comment]
Fixed with https://github.com/scipion-em/scipion-em-tomo/commit/01c1151311fb71cfbfdab565e92bf9d88b40c74c
