### ISSUE TITLE
import subtomogram not working

### ISSUE THREAD

**Issue by EstrellaFG** [scipion-em/scipion-em-tomo#12]
When importing subtomograms **without** coordinates I got the following error:
![Screenshot from 2019-07-11 09-57-18](https://user-images.githubusercontent.com/30145413/61032745-4f3ea800-a3c2-11e9-9ca3-575f8d949fb2.png)

When importing subtomograms **with** coordinates I got this other error:
![Screenshot from 2019-07-11 09-58-17](https://user-images.githubusercontent.com/30145413/61032793-6d0c0d00-a3c2-11e9-9353-2300f0a83c15.png)

**Comment by adrianq** [comment]
Fixed with https://github.com/scipion-em/scipion-em-tomo/pull/6/commits/a311f126dfc6aa288bfff74e9291be953f9fbc1d @EstrellaFG give it a try and reopen otherwise please!
