### ISSUE TITLE
Import subtomo with coordinates

### ISSUE THREAD

**Issue by EstrellaFG** [scipion-em/scipion-em-tomo#13]
Protocol import subtomograms **with** input coordinates 3D still not working. I get the following error (I think is the same as before):
![Screenshot from 2019-07-17 15-44-04](https://user-images.githubusercontent.com/30145413/61380637-0ac37880-a8aa-11e9-8a7f-173b15d90e5e.png)

**Comment by adrianq** [comment]
It looks like it had to do with coordinates and subtomograms with different lengths. Implemented (https://github.com/scipion-em/scipion-em-tomo/pull/6/commits/fb520f306ed46ccce6367b4393d7d115163f9a7e) a validation to provide some more explicit feedback to the user anyway
