### ISSUE TITLE
wrong order import ts movies with pattern

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-tomo#136]
Wrong order when importing TS movies using pattern

![image](https://user-images.githubusercontent.com/6952870/123664302-1dcd7a00-d82f-11eb-9d02-cfce11d64e06.png)
![image](https://user-images.githubusercontent.com/6952870/123664340-29b93c00-d82f-11eb-8bb8-e2c78550ea88.png)
![image](https://user-images.githubusercontent.com/6952870/123664368-33db3a80-d82f-11eb-8133-1bc5e9d378c1.png)

**Comment by fonsecareyna82** [comment]
Since we are showing the acqOrder in that column, this has been fixed

**Comment by azazellochg** [comment]
You are right, it's fixed, just sorting doesn't work, but that we know.
