### ISSUE TITLE
tomo - import tomograms stores the name duplicated if using pattern

### ISSUE THREAD

**Issue by plosana** [scipion-em/scipion-em-tomo#267]
I have three tomograms: TS_43.mrc, TS_45.mrc and TS_54.mrc. If I try to import the tomogram as *.mrc or TS_\*.mrc, he stores the name duplicated as shown in the image:
![image](https://user-images.githubusercontent.com/8470316/201320118-b2f6a1d4-c0f6-43f6-9f49-aedb7482cedf.png)

If I don't use the pattern or * , it imports it well (but I can only import one at a time

![image](https://user-images.githubusercontent.com/8470316/201320473-bc6d0df4-6fee-44ee-af09-6bb299e0b089.png)

I need that it does not duplicate the names, otherwise I cannot link him coordinates or other files

![image](https://user-images.githubusercontent.com/8470316/201320875-4efc62e2-7216-4a28-bc87-0a4118675534.png)

**Comment by JorMaister** [comment]
@plosana, can you paste the pattern used?

**Comment by plosana** [comment]
Sure, these are the different combinations:

- With no * anywhere it works fine

![image](https://user-images.githubusercontent.com/8470316/201326231-258081b7-1c2c-4be5-bad1-6f084671d793.png)

- With * on the directory it duplicates
![image](https://user-images.githubusercontent.com/8470316/201326380-ad61fb46-cdd5-455d-9009-58120fc731f9.png)

- With a specific directory but *.mrc on the pattern works fine

![image](https://user-images.githubusercontent.com/8470316/201326593-c00febb0-9e9b-424f-b7d9-2d38bf95970e.png)

- With * on directory and pattern it duplicates

![image](https://user-images.githubusercontent.com/8470316/201326805-47f4b16d-1b53-41d5-817e-2c423a43e49c.png)

hope it helps

**Comment by pconesa** [comment]
It does A lot. Thanks!

**Comment by fonsecareyna82** [comment]
Yes, this is implemented so as not to duplicate names of tomograms that may have the same name. They are being prefixed with the name of the folder that contains it. The change that I have made consists of putting the name that is expected, but if it were the case that another tomogram was found with a name that has already been assigned, then the prefix will be put.

**Comment by azazellochg** [comment]
I thought no special characters were allowed in the directory path. They should be only used in the pattern. No?

**Comment by pconesa** [comment]
I think we are not doing any validation on special characters.
