### ISSUE TITLE
Problem in viewers in devel

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-tomo#299]
In devel branch, many errors looking like that:
```
 > error when importing from xmipptomo.protocols: type object 'DataViewer' has no attribute 'registerConfig'
   File "/shared/scipion3/plugins/scipion-em-tomo/tomo/viewers/viewers_data.py", line 228, in <module>
   Check the plugin manager (Configuration->Plugins in Scipion manager window) 
   or use 'scipion installp --help --checkUpdates' in the command line to check for upgrades,
   it could be a versions compatibility issue.
```
I noticed that CTF viewer does not work after pulling the latest changes. The master branch is fine.

Cheers
Mohamad

**Comment by pconesa** [comment]
Dear Mohamed. This is needs a change introduced in scipion-em.

Either:

1.- you haven't git pulled scipion-em
2.- You are not in devel mode for scipion-em

If 2, then switch to devel mode or wait until we release scipion-em changes. Could be soon. Tomorrow?

**Comment by MohamadHarastani** [comment]
Dear Pablo
Thanks for the feedback. I am indeed not in the devel mode for scipion-em. I suspected that I needed an update, but I thought `scipion update` should be enough. I prefer to never be on the devel branch of scipion-em, so I will wait for the release.
Cheers
