### ISSUE TITLE
Importing tilt series using tlt or rawtlt file

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-tomo#303]
Hello
I am importing a tilt series that is not aligned using a tlt or rawtlt file.
My tilt series is acquired (actually simulated) as follows:
0, -2, -4, 2, 4, -6, -8, 6, 8, etc.
I put this information in the tlt file and imported to Scipion. The tilt series is imported, but the order is incorrect.
Imod display is wrong, I cannot reconstruct it, and dose accumulation is wrong.
To make reproduce, here is a link with the tilt series and the tlt file, import using tlt option.
https://filesender.renater.fr/?s=download&token=7003d22a-85d8-4453-b62f-45c192cd45ef

Cheers
Mohamad

**Comment by azazellochg** [comment]
Hello @MohamadHarastani , thank you for creating the issue. Importing unsorted tilt-series is currently not working properly, we are aware of this.

**Comment by MohamadHarastani** [comment]
Thanks Grigory for the fast response!

**Comment by pconesa** [comment]
We have assumed the following:
Accquisition scheme does not survive the "stacking". When motion corrected tilts are stacked they are always sorted in angular order.

Nevertheless, we have a couple of branches, not ready yet "allow-unsorted" in tomo, imod and aretomo that deal with this case.

To be honest, apart from simulated data, not sure if this is  "natural case" but it is probably easy to deal with.

**Comment by MohamadHarastani** [comment]
Thanks Pablo. I agree that it is not common, but hey, synthetic data is more important to me than experimental data. My problem is not sorting, I can do it. It is importing the right the dose. I worked hard to simulate dose damage on synthetic data, and I need this semi-symmetric scheme in particular. 
I thought by giving the right tlt file it should read it, sort the tilt series and give the right information on the dose. The same scheme is properly detected if I import an mdoc file right?
What is your recommendation to so that this tilt series is improted to Scipion, sorted and with proper dose information.

**Comment by pconesa** [comment]
Safest import of tilt series is with mdocs, but is not trivial to generate.

In any case, the branches dealing with unsorted stacked tilt series are using mdoc.

Not sure if you can use the "alternative import" with the dose. specifying a tlt text file with the angles. For sure, if you go down this route you'll need the specific branches.

**Comment by MohamadHarastani** [comment]
Thanks Pablo!
Today is my last day in the office. I am leaving for a couple of days and
will be back just after new year. Probably I better not go that route at
this moment. I will probably ask your help by then on how to use the
alternative import.
Happy new year 😊

**Comment by pconesa** [comment]
Sure, happy new year. We talk on 2023!

**Comment by MohamadHarastani** [comment]
I found a way to sort the tilt series before importing to scipion. However, this sorting that I can up with depends on both imod and eman and is kind of dirty. The PR linked to this issue solves the problem of importing the accumulated dose after sorting the tilt series.
Cheers

**Comment by pconesa** [comment]
we have branches in tomo, imod and aretomo names "allow-unsorted-ts" that will eventually cope with this case but have been only tested by me. So far they are staled for can reactivate them if we find unsorted ts to be frequent.

**Comment by MohamadHarastani** [comment]
I think it is mostly for synthetic data. At first, I wanted to keep the tilt-series simulated with dose symmetry unsorted since there was no other way to import dose accumulation correctly after sorting. Now, my problem is solved.
