### ISSUE TITLE
report alignment in tilt-series movies alignment protocols

### ISSUE THREAD

**Issue by fede-pe** [scipion-em/scipion-em-tomo#335]
The requirement is equivalent to how it is implemented SPA. In order to develop consensus/quality analysis protocols in Scipion, the tilt-series movies with the assigned alignments are needed. Just an output SetOfTiltSeriesMovies with the same information as the input one plus a transform object containing the alignment is enough.

**Comment by azazellochg** [comment]
duplicate of #128
