### ISSUE TITLE
Streaming import of Tilt-SeriesMovies doesn't work

### ISSUE THREAD

**Issue by olofsvensson** [scipion-em/scipion-em-tomo#349]
The ESRF [CM01](https://www.esrf.fr/CM01) instrument will soon (May/June 2023) start supporting CryoET for users, as well as single particle CryoEM. I have therefore started to develop a new Scipion pipeline for CryoET. For testing this pipeline I am simulating CryoET data collections by copying movies to the same file location as the CM01 EPU software will use.

I'm trying to use the 'Tilt-SeriesMovies import protocol':
https://github.com/scipion-em/scipion-em-tomo/blob/eb5188da6e79fcd2d792ceed9489f855ed2c53f5/tomo/protocols/protocol_ts_import.py#L896

The protocol works fine in non-streaming mode, i.e. it correctly import movies and assigns the movies to tilt-series based on the information in the movie file name. When I try to use the protocol in streaming mode it does not work:

- Any files already on the file system are correctly imported.
- Any new files appearing (copied) belonging to a tilt-serie already started are not imported.
- When movies belonging to a new tilt-serie are detected the first ones are imported but then the import stops.

I suspect the problem is linked to this code:

https://github.com/scipion-em/scipion-em-tomo/blob/eb5188da6e79fcd2d792ceed9489f855ed2c53f5/tomo/protocols/protocol_ts_import.py#L705-L706

I guess this code is preventing new movies belong to a tilt-serie that has already been registered to be detected.

Any help in getting this protocol to work in streaming mode is greatly appreciated!

**Comment by pconesa** [comment]
Hi Olof, at the end it was much safer to do the streaming via SPA (import and motion correction) and then use the "tilt series composer" protocol.

I add Alberto who did the streamification this way

**Comment by albertmena** [comment]
Hi @olofsvensson,
Yes, the way we have the streaming in tomo is:

1. protocol import movies (SPA) 
2. protocol Align movies (motioncorr, FlexAlign...) (SPA)
3. protocol composeTS (tomo) works in streaming

**Comment by olofsvensson** [comment]
Hi @albertmena and @pconesa ,
Thanks for feedback! 

The ProtImportTsMovies protocol doesn't work in streaming even if there is a streaming option... Is this streaming option going to be fixed? If not I guess the option could be removed?

I have tried the workflow ProtImportMovies -> ProtMotionCorr -> ProtComposeTS in streaming (simulated data collection) but it didn't work as expected... I didn't get a tilt serie output even if all movies were motion corrected and the protocol finished. I'll open a new issue for this problem.

**Comment by albertmena** [comment]
> Hi @albertmena and @pconesa , Thanks for feedback!
> 
> The ProtImportTsMovies protocol doesn't work in streaming even if there is a streaming option... Is this streaming option going to be fixed? If not I guess the option could be removed?
> 
> I have tried the workflow ProtImportMovies -> ProtMotionCorr -> ProtComposeTS in streaming (simulated data collection) but it didn't work as expected... I didn't get a tilt serie output even if all movies were motion corrected and the protocol finished. I'll open a new issue for this problem.

Ok, maybe we can discuss the composeTS problem in a specific issue.
