### ISSUE TITLE
Problem getting ProtComposeTS to work in streaming

### ISSUE THREAD

**Issue by olofsvensson** [scipion-em/scipion-em-tomo#353]
As discussed in https://github.com/scipion-em/scipion-em-tomo/issues/349, I have problems getting the "Compose Tilt-Series" protocol to work in streaming.
The first thing to do is to verify that the mdoc file generated by the EPU software is valid. I'll attach an example mdoc file to this issue.

**Comment by olofsvensson** [comment]
I had to rename the file with an .txt extension for github to accept it:
[grid1_Position_11.mdoc.txt](https://github.com/scipion-em/scipion-em-tomo/files/11286084/grid1_Position_11.mdoc.txt)

**Comment by olofsvensson** [comment]
@albertmena , can you please have a look on the mdoc file and see if it should work with ProtComposeTS?

**Comment by pconesa** [comment]
Is there any error message? A first look seems the right one, but need a more thorugh examination

**Comment by olofsvensson** [comment]
There are no error messages. I try to run the following Scipion workflow:
![image](https://user-images.githubusercontent.com/1306808/233402880-69b6e71b-4b75-4ee5-abbd-4b8074dc7994.png)
The log of the ProtComposeTS looks like this:
```
00001:   Logging configured. STDOUT --> /mnt/multipath-shares/data/visitor/mx2112/cm01/20230420/PROCESSED_DATA/grid1_2/mx2112_test_grid1_20230420-161149/Runs/000201_ProtComposeTS/logs/run.stdout , STDERR --> /mnt/multipath-shares/data/visitor/mx2112/cm01/20230420/PROCESSED_DATA/grid1_2/mx2112_test_grid1_20230420-161149/Runs/000201_ProtComposeTS/logs/run.stderr
00002:   RUNNING PROTOCOL -----------------
00003:   Protocol starts
00004:   Hostname: scisoft10.esrf.fr
00005:   PID: 4146529
00006:   pyworkflow: 3.0.31
00007:   plugin: tomo
00008:   plugin v: 3.1.5
00009:   plugin binary v: 
00010:   currentDir: /mnt/multipath-shares/data/visitor/mx2112/cm01/20230420/PROCESSED_DATA/grid1_2/mx2112_test_grid1_20230420-161149
00011:   workingDir: Runs/000201_ProtComposeTS
00012:   runMode: Continue
00013:             MPI: 1
00014:         threads: 3
00015:    Starting at step: 1
00016:    Running steps 
00017:   STARTED: _initialize, step 1, time 2023-04-20 16:13:37.036726
00018:   FINISHED: _initialize, step 1, time 2023-04-20 16:13:37.051047
00019:   STARTED: readMdoc, step 3, time 2023-04-20 16:22:51.215450
00020:   mdoc file to read: /data/visitor/mx2112/cm01/20230420/RAW_DATA/grid1_2/grid1_Position_12.mdoc
00021:   mdoc file to read: /data/visitor/mx2112/cm01/20230420/RAW_DATA/grid1_2/grid1_Position_12.mdoc
00022:   mdoc file to read: /data/visitor/mx2112/cm01/20230420/RAW_DATA/grid1_2/grid1_Position_12.mdoc
00023:   Loading input db: Runs/000066_ProtMotionCorr/micrographs_dose-weighted.sqlite
00024:   Tilts in the mdoc file: 41 Micrographs  abailables: 32
00025:   Waiting next micrograph...
00026:   Loading input db: Runs/000066_ProtMotionCorr/micrographs_dose-weighted.sqlite
00027:   FINISHED: readMdoc, step 3, time 2023-04-20 16:26:04.444667
```
Even there are 41 micrographs at the input there is no output tilt serie:
![image](https://user-images.githubusercontent.com/1306808/233403648-3bad780a-aa8b-4537-a36f-06b91c7dded8.png)

**Comment by pconesa** [comment]
I see, "abailables" (already changed here)

So, mdoc parsing has gone fine. THis is probably the best news... but 
for some reason it has not generated the tilt series. Need to 
investigate why.

**Comment by albertmena** [comment]
Hello @olofsvensson,
I'm working in a refactor of the protocol, I think will fix the issue because is related to the time waiting the next micrograph. I hope next week will be in devel.
Meanwhile, you can increase the streaming parameter _time4NextMic_, and to see how the protocol works you could run the test:
`scipion3 tests tomo.tests.test_compose_TS.TestTomoComposeTS`
I will report in this issue about the news
Thank you

**Comment by albertmena** [comment]
Hi again, 
The refactoring and fixing is now in devel, you can update the repository and try again.
Please tell us about the experience.

**Comment by olofsvensson** [comment]
Hi, I just tested and it's now working fine! Thanks a lot for the help!
I noticed that there are still three typos (pointed out by Pablo above) in the code: "available" on lines 44, 126 and 276.

**Comment by albertmena** [comment]
Thanks, gald to hear it works fine for you, I'll take into account. And let us know any issue, enhancement...

**Comment by albertmena** [comment]
Just for your information, the protocol [Aretomo](https://github.com/scipion-em/scipion-em-aretomo/blob/master/aretomo/protocols/protocol_aretomo.py) is now in streaming, you can connect the output of composeTS with the ARETOMO protocol.
