### ISSUE TITLE
SetOfTomoMask cannot ve visualized

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-tomo#373]
The default viewer for visualizing a set of tomo mask is not imod, it seems to be chimera. If we do right click on the output to open the tomo masks with imod, then imod still does not open them.

**Comment by azazellochg** [comment]
@Vilax the workaround is right click on an item and select correct viewer
@fonsecareyna82 why do we have right click implemented in both tomo and imod plugins? Essentially the user has to select the needed viewer twice, first in the project window and then in the viewer list dialog:

```
    def getObjectActions(self, obj):
        actions = []
        if not self.isInteractive:
            viewers = Domain.findViewers(obj.getClassName(),
                                         pwviewer.DESKTOP_TKINTER)
            for viewerClass in viewers:
                def createViewer(viewerClass, obj):
                    proj = self.protocol.getProject()
                    item = self.objs[obj.getObjId()]  # to load mapper

                    return lambda: viewerClass(project=proj, protocol=self.protocol).visualize(item)
                actions.append(('Open with %s' % viewerClass.__name__,
                                createViewer(viewerClass, obj)))
        return actions
```

**Comment by azazellochg** [comment]
this is now fixed in https://github.com/scipion-em/scipion-em-imod/pull/211
