### ISSUE TITLE
import coordinates does not rescale

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-tomo#398]
The import coordinates requires the coordinates files and a set of tomograms. However, in many cases the tomograms have different pixel size than the coordinates. In such situations the import is not possible because the the coordiantes are not scaled to the tomogram pixel size. The import should check if the that both pixel sizes are the same and if not to carry out an scaling

**Comment by JorMaister** [comment]
Solved in https://github.com/scipion-em/scipion-em-tomo/pull/402
