### ISSUE TITLE
Import CTF - unable to import the CTFs from reliontomo test dataset

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em-tomo#446]
Description:

- The image attached shows the working file directory elements.

- TS imported correctly: tsId present are TS_03, TS_54.

- Protocol log files attached.

![Screenshot from 2024-01-22 11-08-05](https://github.com/scipion-em/scipion-em-tomo/assets/54907551/0351c598-e110-47f4-89e3-4b0a4bc3743b)
[run.stderr.txt](https://github.com/scipion-em/scipion-em-tomo/files/14009058/run.stderr.txt)
[run.stdout.txt](https://github.com/scipion-em/scipion-em-tomo/files/14009059/run.stdout.txt)

**Comment by azazellochg** [comment]
thank you @JorMaister , I'll have a look

**Comment by JorMaister** [comment]
Update: 

I noticed that in the case of TS_03, the defocus file has 40 lines, while the TS has 41 angles, and that is the cause of the error... We're adding the code the capability to allow the importing of TS and CTF considering the exclude views if there are any. It does not solve this problem as we don't now in this case whch view was excluded, but may cover the rest of the cases. I suggest to skip the CTFs in which this size mismatching is found and report the user in the summary or something. I can do it myself if you want, @azazellochg.

**Comment by azazellochg** [comment]
sure, go ahead, you will fix it faster than me :)

**Comment by JorMaister** [comment]
Ok then, I'll assign this issue to myself.
