### ISSUE TITLE
Import tilt series with *.mrc stop working

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-tomo#517]
Since the moment we introduced the patterns like {} the normal pattern like "*/*.mrc" used in some workflow templates has stop working.

**Comment by JorMaister** [comment]
Oh, I forgot to close this. @azazellochg, we allow mrc, mrcs, and st, which compose the different scenarios we've found

**Comment by azazellochg** [comment]
Then I suppose the help is outdated: https://github.com/scipion-em/scipion-em-tomo/blob/devel/tomo/protocols/protocol_ts_import.py#L116
