### ISSUE TITLE
ctf viewer not working for re-stacked TS

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-tomo#524]
Reproduce:
1) exclude first tilt and restack
2) run ctffind
3) press analyse results

Error:
```
File "/home/gsharov/soft/scipion-em-plugins/scipion-em-tomo/tomo/viewers/views_tkinter_tree.py", line 1268, in getObjectInf
tiltAngle = ts[int(text)].getTiltAngle()
AttributeError: 'NoneType' object has no attribute 'getTiltAngle'
```
The reason is that [here](https://github.com/scipion-em/scipion-em-tomo/blame/devel/tomo/viewers/views_tkinter_tree.py#L495) we copy the id, so in my case, the first tilt image of the restacked TS has objId 2.

**Comment by pconesa** [comment]
I think @fonsecareyna82 had also a fix for this in another branch?
