### ISSUE TITLE
Wrong cite for protocol 

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-em-tomo#66]
Protocol 'map back subtomos' has wrong 'Cite', see the attachement

![image](https://user-images.githubusercontent.com/28389367/87539767-ccb88a80-c69e-11ea-9b74-c717ee81019b.png)

**Comment by azazellochg** [comment]
that's some ugly fonts :)

**Comment by EstrellaFG** [comment]
This protocol is from other plugin, scipion-em-xmipptomo, and actually cites are wrong in all protocols of that plugin. I will fix it there. Thanks @DStrelak!
